"""
Interactive polygon editor for semi-automatic auto-crop review regions.

This tool updates the exported review template JSON in place. The primary goal
is to make focus / ignore region definition practical for users who prefer to
draw directly on the overview image rather than typing coordinates.

Supported workflow:

1. Open a review template JSON produced by export_auto_crop_training_data.py.
2. Draw one or more focus polygons.
3. Draw one or more ignore polygons.
4. Save the updated review JSON plus a preview overlay image.
5. Re-run propose_auto_crop_candidates.py with --review-json.
"""

from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Polygon as MplPolygon
from matplotlib.widgets import Button
from PIL import Image, ImageDraw


FOCUS_COLOR = (0.12, 0.78, 0.42, 0.95)
FOCUS_FILL = (0.12, 0.78, 0.42, 0.16)
IGNORE_COLOR = (0.88, 0.28, 0.28, 0.95)
IGNORE_FILL = (0.88, 0.28, 0.28, 0.18)
ACTIVE_FOCUS = (0.25, 0.95, 0.55, 1.0)
ACTIVE_IGNORE = (1.0, 0.48, 0.36, 1.0)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Interactively draw focus / ignore polygons for auto-crop review."
    )
    parser.add_argument(
        "--review-json",
        required=True,
        help="Path to a review template JSON generated by the export script.",
    )
    parser.add_argument(
        "--start-mode",
        choices=("focus", "ignore"),
        default="focus",
        help="Drawing mode selected when the editor opens.",
    )
    parser.add_argument(
        "--preview-path",
        help=(
            "Optional path for the saved region preview image. Defaults to "
            "<review_json_stem>_regions_preview.png beside the review JSON."
        ),
    )
    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def normalize_point(x: float, y: float, width: int, height: int) -> list[int]:
    px = max(0, min(int(round(x)), width - 1))
    py = max(0, min(int(round(y)), height - 1))
    return [px, py]


def shape_to_points(shape: dict[str, Any], width: int, height: int) -> list[list[int]]:
    if "points" in shape:
        return [normalize_point(point[0], point[1], width, height) for point in shape["points"]]

    if "bbox_xyxy" in shape:
        x1, y1, x2, y2 = shape["bbox_xyxy"]
        return [
            normalize_point(x1, y1, width, height),
            normalize_point(x2, y1, width, height),
            normalize_point(x2, y2, width, height),
            normalize_point(x1, y2, width, height),
        ]

    raise ValueError(f"Unsupported region shape: {shape}")


def polygon_entry(points: list[list[int]]) -> dict[str, Any]:
    return {"type": "polygon", "points": points}


def polygon_label_center(points: list[list[int]]) -> tuple[float, float]:
    array = np.array(points, dtype=np.float32)
    return float(array[:, 0].mean()), float(array[:, 1].mean())


def render_preview(
    image: np.ndarray,
    focus_regions: list[dict[str, Any]],
    ignore_regions: list[dict[str, Any]],
    output_path: Path,
) -> None:
    rgb = np.repeat(image[..., None], 3, axis=2)
    base = Image.fromarray(rgb).convert("RGBA")
    overlay = Image.new("RGBA", base.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    for region in focus_regions:
        points = shape_to_points(region, width=image.shape[1], height=image.shape[0])
        draw.polygon(points, fill=(32, 188, 92, 46), outline=(28, 202, 108, 220))

    for region in ignore_regions:
        points = shape_to_points(region, width=image.shape[1], height=image.shape[0])
        draw.polygon(points, fill=(212, 64, 64, 52), outline=(232, 72, 72, 228))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    Image.alpha_composite(base, overlay).convert("RGB").save(output_path)


class RegionEditor:
    def __init__(
        self,
        image: np.ndarray,
        review_json: Path,
        review_data: dict[str, Any],
        preview_path: Path,
        start_mode: str,
    ) -> None:
        self.image = image
        self.review_json = review_json
        self.review_data = review_data
        self.preview_path = preview_path
        self.height, self.width = image.shape
        self.focus_regions = copy.deepcopy(review_data.get("focus_regions", []))
        self.ignore_regions = copy.deepcopy(review_data.get("ignore_regions", []))
        self.current_mode = start_mode
        self.current_points: list[list[int]] = []
        self.dirty = False
        self._has_drawn = False

        self.fig, self.ax = plt.subplots(figsize=(14, 8))
        self.fig.subplots_adjust(left=0.03, right=0.99, top=0.92, bottom=0.15)
        try:
            self.fig.canvas.manager.set_window_title("Auto Crop Region Editor")
        except Exception:
            pass

        self._build_buttons()
        self._connect_events()
        self._draw()

    def _build_buttons(self) -> None:
        specs = [
            ("Focus", self._focus_mode, 0.04),
            ("Ignore", self._ignore_mode, 0.14),
            ("Undo Pt", self._undo_point, 0.26),
            ("Undo Poly", self._undo_region, 0.36),
            ("Clear Mode", self._clear_mode_regions, 0.48),
            ("Save", self.save, 0.64),
            ("Quit", self._quit, 0.74),
        ]
        self.buttons = []
        for label, callback, left in specs:
            ax_button = self.fig.add_axes([left, 0.04, 0.09, 0.055])
            button = Button(ax_button, label)
            button.on_clicked(callback)
            self.buttons.append(button)

    def _connect_events(self) -> None:
        self.fig.canvas.mpl_connect("button_press_event", self._on_click)
        self.fig.canvas.mpl_connect("key_press_event", self._on_key)
        self.fig.canvas.mpl_connect("close_event", self._on_close)

    def _toolbar_is_busy(self) -> bool:
        toolbar = getattr(self.fig.canvas, "toolbar", None)
        if toolbar is None:
            return False
        return bool(getattr(toolbar, "mode", ""))

    def _active_edge_color(self) -> tuple[float, float, float, float]:
        if self.current_mode == "focus":
            return ACTIVE_FOCUS
        return ACTIVE_IGNORE

    def _active_fill_color(self) -> tuple[float, float, float, float]:
        if self.current_mode == "focus":
            return FOCUS_FILL
        return IGNORE_FILL

    def _mode_regions(self) -> list[dict[str, Any]]:
        if self.current_mode == "focus":
            return self.focus_regions
        return self.ignore_regions

    def _status_line(self) -> str:
        return (
            f"Mode: {self.current_mode.upper()} | "
            f"focus={len(self.focus_regions)} ignore={len(self.ignore_regions)} | "
            f"current_vertices={len(self.current_points)} | "
            f"{'unsaved changes' if self.dirty else 'saved'}"
        )

    def _draw_regions(
        self,
        regions: list[dict[str, Any]],
        edge_color: tuple[float, float, float, float],
        fill_color: tuple[float, float, float, float],
        prefix: str,
    ) -> None:
        for index, region in enumerate(regions, start=1):
            points = shape_to_points(region, width=self.width, height=self.height)
            patch = MplPolygon(
                points,
                closed=True,
                edgecolor=edge_color,
                facecolor=fill_color,
                linewidth=2.0,
            )
            self.ax.add_patch(patch)
            cx, cy = polygon_label_center(points)
            self.ax.text(
                cx,
                cy,
                f"{prefix}{index}",
                color=edge_color,
                fontsize=10,
                ha="center",
                va="center",
                bbox={"facecolor": (0, 0, 0, 0.42), "edgecolor": "none", "pad": 1.5},
            )

    def _draw_current_polygon(self) -> None:
        if not self.current_points:
            return

        xs = [point[0] for point in self.current_points]
        ys = [point[1] for point in self.current_points]
        self.ax.plot(
            xs,
            ys,
            color=self._active_edge_color(),
            linewidth=2.0,
            marker="o",
            markersize=4.0,
        )
        if len(self.current_points) >= 3:
            patch = MplPolygon(
                self.current_points,
                closed=True,
                edgecolor=self._active_edge_color(),
                facecolor=self._active_fill_color(),
                linewidth=1.3,
                linestyle="--",
            )
            self.ax.add_patch(patch)

    def _draw(self) -> None:
        xlim = self.ax.get_xlim() if self._has_drawn else None
        ylim = self.ax.get_ylim() if self._has_drawn else None

        self.ax.clear()
        self.ax.imshow(self.image, cmap="gray", vmin=0, vmax=255)
        self.ax.set_xticks([])
        self.ax.set_yticks([])
        self.ax.set_title(self._status_line(), fontsize=11)

        self._draw_regions(self.focus_regions, FOCUS_COLOR, FOCUS_FILL, "F")
        self._draw_regions(self.ignore_regions, IGNORE_COLOR, IGNORE_FILL, "I")
        self._draw_current_polygon()

        help_text = (
            "Left click: add vertex | Enter or right click: finish polygon | "
            "Backspace: undo point | Esc: cancel current polygon | "
            "F/I: switch mode | U: undo last polygon | C: clear current mode | "
            "S: save"
        )
        self.fig.suptitle(help_text, fontsize=10, y=0.985)

        if xlim is not None and ylim is not None:
            self.ax.set_xlim(xlim)
            self.ax.set_ylim(ylim)

        self.fig.canvas.draw_idle()
        self._has_drawn = True

    def _add_point(self, x: float, y: float) -> None:
        point = normalize_point(x, y, self.width, self.height)
        if self.current_points and self.current_points[-1] == point:
            return
        self.current_points.append(point)
        self._draw()

    def _finalize_polygon(self) -> None:
        if len(self.current_points) < 3:
            print("Current polygon needs at least 3 vertices.")
            return

        deduped: list[list[int]] = []
        for point in self.current_points:
            if deduped and deduped[-1] == point:
                continue
            deduped.append(point)
        if len(deduped) >= 2 and deduped[0] == deduped[-1]:
            deduped.pop()

        if len(deduped) < 3:
            print("Current polygon collapsed after deduplication.")
            return

        self._mode_regions().append(polygon_entry(deduped))
        self.current_points = []
        self.dirty = True
        self._draw()
        print(f"Added {self.current_mode} polygon. Total {self.current_mode}: {len(self._mode_regions())}")

    def _finalize_if_possible(self) -> None:
        if len(self.current_points) >= 3:
            print("Auto-finalizing the current polygon before save.")
            self._finalize_polygon()
            return
        if self.current_points:
            print(
                "Current polygon has fewer than 3 vertices and was not saved. "
                "Add more points or press Esc to cancel it."
            )

    def _undo_point(self, _event: Any | None = None) -> None:
        if not self.current_points:
            print("No current vertex to undo.")
            return
        self.current_points.pop()
        self._draw()

    def _undo_region(self, _event: Any | None = None) -> None:
        regions = self._mode_regions()
        if not regions:
            print(f"No saved {self.current_mode} polygon to undo.")
            return
        regions.pop()
        self.dirty = True
        self._draw()

    def _clear_mode_regions(self, _event: Any | None = None) -> None:
        regions = self._mode_regions()
        if not regions and not self.current_points:
            print(f"No {self.current_mode} regions to clear.")
            return
        regions.clear()
        self.current_points = []
        self.dirty = True
        self._draw()

    def _focus_mode(self, _event: Any | None = None) -> None:
        self.current_mode = "focus"
        self._draw()

    def _ignore_mode(self, _event: Any | None = None) -> None:
        self.current_mode = "ignore"
        self._draw()

    def _quit(self, _event: Any | None = None) -> None:
        plt.close(self.fig)

    def _save_review_data(self) -> None:
        self.review_data["focus_regions"] = self.focus_regions
        self.review_data["ignore_regions"] = self.ignore_regions
        self.review_json.write_text(
            json.dumps(self.review_data, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        render_preview(
            image=self.image,
            focus_regions=self.focus_regions,
            ignore_regions=self.ignore_regions,
            output_path=self.preview_path,
        )
        self.dirty = False

    def save(self, _event: Any | None = None) -> None:
        self._finalize_if_possible()
        self._save_review_data()
        self._draw()
        print(f"Saved review JSON: {self.review_json}")
        print(f"Saved region preview: {self.preview_path}")
        print(
            f"Saved counts -> focus: {len(self.focus_regions)}, "
            f"ignore: {len(self.ignore_regions)}"
        )

    def _on_click(self, event: Any) -> None:
        if self._toolbar_is_busy():
            return
        if event.inaxes != self.ax:
            return
        if event.xdata is None or event.ydata is None:
            return

        if event.button == 1:
            self._add_point(event.xdata, event.ydata)
            return

        if event.button == 3:
            self._finalize_polygon()

    def _on_key(self, event: Any) -> None:
        key = (event.key or "").lower()
        if key == "f":
            self._focus_mode()
            return
        if key == "i":
            self._ignore_mode()
            return
        if key in {"enter", "return"}:
            self._finalize_polygon()
            return
        if key == "backspace":
            self._undo_point()
            return
        if key == "escape":
            self.current_points = []
            self._draw()
            return
        if key == "u":
            self._undo_region()
            return
        if key == "c":
            self._clear_mode_regions()
            return
        if key == "s":
            self.save()
            return
        if key == "q":
            self._quit()

    def _on_close(self, _event: Any) -> None:
        if self.dirty:
            print("Editor closed with unsaved changes. Press S or click Save before closing next time.")


def main() -> None:
    args = parse_args()
    review_json = Path(args.review_json).resolve()
    if not review_json.exists():
        raise FileNotFoundError(f"Review JSON not found: {review_json}")

    review_data = load_json(review_json)
    source_image = Path(review_data["source_image"])
    if not source_image.exists():
        raise FileNotFoundError(f"Source image not found: {source_image}")

    image = np.array(Image.open(source_image).convert("L"), dtype=np.uint8)
    preview_path = (
        Path(args.preview_path).resolve()
        if args.preview_path
        else review_json.with_name(f"{review_json.stem}_regions_preview.png")
    )

    print(f"Opening review JSON: {review_json}")
    print(f"Source image: {source_image}")
    print("Controls:")
    print("  Left click: add vertex")
    print("  Right click or Enter: finish polygon")
    print("  Backspace: undo current vertex")
    print("  Esc: cancel current polygon")
    print("  F / I: switch focus or ignore mode")
    print("  U: undo last saved polygon in current mode")
    print("  C: clear all polygons in current mode")
    print("  S: save JSON and preview image")
    print("  Q: quit")

    editor = RegionEditor(
        image=image,
        review_json=review_json,
        review_data=review_data,
        preview_path=preview_path,
        start_mode=args.start_mode,
    )
    plt.show()


if __name__ == "__main__":
    main()
